version: 2
report_sizes: true

before:
  hooks:
    - go mod tidy

gomod:
  proxy: true
  mod: mod
  env:
    - GOPROXY=https://proxy.golang.org,direct
    - GOSUMDB=sum.golang.org
    - GOPRIVATE=github.com/jimmystewpot/dns-preload

builds:
  - id: "pdns-statsd-proxy"
    main: ./cmd/pdns-statsd-proxy
    binary: "pdns-statsd-proxy"
    flags:
      - -trimpath
      - -buildvcs=true
    ldflags:
      - -w -s
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - freebsd
      - linux
      - netbsd
      - openbsd
      - windows

    goarch:
      - amd64
      - arm
      - arm64

    goarm:
      - 6
      - 7

    goamd64:
      - v1

    ignore:
      - goos: darwin
        goarch: arm
        goarm: 6
      - goos: darwin
        goarch: arm
        goarm: 7
      - goos: windows
        goarch: 386
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: armv6
      - goos: windows
        goarch: armv7

    mod_timestamp: "{{ .CommitTimestamp }}"
    skip: false
    no_unique_dist_dir: false
    no_main_check: true

nfpms:
  - id: pdns-statsd-proxy
    package_name: pdns-statsd-proxy
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    ids:
      - pdns-statsd-proxy
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    maintainer: "{{ .Env.GORELEASER_MAINTAINER }}"
    description: "PowerDNS statistics to statsd bridge"
    license: "MIT"
    scripts:
      postinstall: packaging/postinstall.sh
      postremove: packaging/postremove.sh
    contents:
      - src: systemd/pdns-statsd-proxy.service
        dst: /lib/systemd/system/pdns-statsd-proxy.service
        file_info:
          mode: 0644
      - src: systemd/pdns-statsd-proxy.service
        dst: /usr/lib/systemd/system/pdns-statsd-proxy.service
        file_info:
          mode: 0644
      - src: README.md
        dst: /usr/share/doc/pdns-statsd-proxy/README.md
        file_info:
          mode: 0644
      - src: LICENSE
        dst: /usr/share/doc/pdns-statsd-proxy/LICENSE
        file_info:
          mode: 0644

checksum:
  name_template: '{{ .ArtifactName }}.{{ .Algorithm }}'
  algorithm: sha256
  split: true
  disable: false

release:
  mode: append
  skip_upload: false

sboms:
  - id: pdns-statsd-proxy

    documents:
      - "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ .Target }}.sbom.json"

    # Path to the SBOM generator command
    #
    # Note: the process CWD will be set to the same location as "dist"
    #
    # Default: 'syft'.
    cmd: "syft"

    args: ["$artifact", "--output", "spdx-json=$document"]

    env:
      - SYFT_GOLANG_SEARCH_LOCAL_MOD_CACHE_LICENSES=true
      - SYFT_GOLANG_SEARCH_REMOTE_LICENSES=true

    # Which artifacts to catalog.
    #
    # Valid options are:
    # - any:        let the SBOM tool decide which artifacts available in
    #               the cwd should be cataloged
    # - source:     source archive
    # - package:    Linux packages (deb, rpm, apk, etc)
    # - installer:  Windows MSI installers (Pro only)
    # - diskimage:  macOS DMG disk images (Pro only)
    # - archive:    archives from archive pipe
    # - binary:     binaries output from the build stage
    #
    # Default: 'archive'.
    artifacts: binary

    # IDs of the artifacts to catalog.
    #
    # If `artifacts` is "source" or "any" then this fields has no effect.
    #ids:
    #  - foo
    #   - bar
    