name: Unit Test, Lint and Build

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - master
  workflow_dispatch: {}
  schedule:
    - cron: "1 1 2 * *"

permissions:
  pull-requests: read

jobs:
  build_and_test:
    name: "Lint Test and Build"
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Test and Build
        run: make build
  
  snyk-security-scan:
    name: "Snyk Security Scan"
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Snyk Security Scanning
        uses: snyk/actions/golang@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SNYK_TOKEN: ${{ secrets.SNYK_API_TOKEN }}
          SNYK_ORG_ID: ${{ secrets.SNYK_ORG_ID }}
