name: goreleaser

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  actions: none
  artifact-metadata: none
  attestations: none
  checks: none
  deployments: none
  id-token: none
  issues: none
  models: none
  discussions: none
  packages: none
  pages: none
  pull-requests: none
  security-events: none
  statuses: none

jobs:
  goreleaser:
    runs-on: ubuntu-24.04
    steps:
      - 
        name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          fetch-depth: 0
      - 
        name: Set up Go
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00
        with:
          go-version: stable
      -
        name: Install Syft
        run: go install github.com/anchore/syft/cmd/syft@latest
      - 
        name: Run GoReleaser Release
        uses: goreleaser/goreleaser-action@f06c13b6b1a9625abc9e6e439d9c05a8f2190e94
        with:
          distribution: goreleaser
          version: '~> v2'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GORELEASER_MAINTAINER: ${{ vars.GORELEASER_MAINTAINER || vars.GORELEASER_MAINTANER }}
