name: SonarCloud project analysis

on:
  push:
    branches:
      - main
      - '**'
  pull_request:
    branches: [ main ]
    types: [ opened ]
  workflow_dispatch:

permissions:
  pull-requests: read # allows SonarCloud to decorate PRs with analysis results

jobs:
  Analysis:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19'
      - name: Install Test Dependencies
        run: make deps
      - name: Run golangci-lint
        run: make lint
      - name: Run Tests
        run: make test
      - name: Analyze project with SonarCloud
        # You can pin the exact commit or the version.
        # uses: SonarSource/sonarcloud-github-action@de2e56b42aa84d0b1c5b622644ac17e505c9a049
        uses: SonarSource/sonarcloud-github-action@v1.8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          # Additional arguments for the sonarcloud scanner
          args:
            -Dsonar.tests=.
            -Dsonar.projectBaseDir=.
            -Dsonar.sources=.
            -Dsonar.projectKey=jimmystewpot_pdns-statsd-proxy
            -Dsonar.organization=jimmystewpot
            -Dsonar.go.tests.reportPaths=reports/testreport.json
            -Dsonar.go.coverage.reportPaths=reports/coverage.txt
            -Dsonar.go.golint.reportPaths=reports/checkstyle-lint.xml
            -Dsonar.test.inclusions=**/*_test.go
            -Dsonar.scm.disabled
            -Dsonar.sourceEncoding=UTF-8
            -Dsonar.verbose=true
      - name: codecov
        uses: codecov/codecov-action@v3
        with:
          directory: reports/